---
title: "Publications Test"
date: '2020-06-25T00:00:00Z'
reading_time: no
output:
  md_document:
    variant: commonmark
    preserve_yaml: true
profile: no
comments: no
share: no
---

```{r setup, include = FALSE}

# Load packages
library(tidyverse)
library(here)

# Load cv data  
my_data <- read_csv(here("static", "data", "pubs.csv"))

years <- unique(my_data$year)

```


```{r publications, echo = FALSE, results = "asis"}
for(year in years){
  cat(paste("\n", "## ", year ,sep=""))
  thisyear <- my_data[my_data$year == year,]
  if(dim(thisyear)[1] > 0){
    cat("\n<ul>")
    for(i in 1:(dim(thisyear)[1])){
      cat(paste("\n<li>",sep = ""))
      cat(paste(thisyear$content[i]))
      
      infodrop <- as_tibble(t(thisyear[i, c("pdf", "code", "data")]), rownames = "info", .name_repair = ~ c("V1")) %>%
        drop_na()
      
      if(nrow(infodrop) == 1){
        cat(" <a href=\"",infodrop$V1[1],"\">",infodrop$info[1],"</a>", sep = "")  
      }
      
      if(nrow(infodrop) == 2){
        cat(" <a href=\"",infodrop$V1[1],"\">",infodrop$info[1],"</a> | ", 
            "<a href=\"",infodrop$V1[2],"\">",infodrop$info[2],"</a>", 
            sep = "")  
      }
      
      if(nrow(infodrop) == 3){
        cat(" <a href=\"",infodrop$V1[1],"\">",infodrop$info[1],"</a> | ", 
            "<a href=\"",infodrop$V1[2],"\">",infodrop$info[2],"</a> | ", 
            "<a href=\"",infodrop$V1[3],"\">",infodrop$info[3],"</a>", 
            sep = "")  
      }
      
      if(nrow(infodrop) == 4){
        cat(" <a href=\"",infodrop$V1[1],"\">",infodrop$info[1],"</a> | ", 
            "<a href=\"",infodrop$V1[2],"\">",infodrop$info[2],"</a> | ", 
            "<a href=\"",infodrop$V1[3],"\">",infodrop$info[3],"</a> | ", 
            "<a href=\"",infodrop$V1[4],"\">",infodrop$info[4],"</a>", 
            sep = "")  
      }
      
    }
    cat("\n</ul>")
  }
}
```
